export const FIELDS_BY_KIND = {
  VAT_PURCHASE: ["document_number", "issue_date", "receipt_date", "contractor_nip", "contractor_name", "net", "vat", "gross", "register_name", "vat_period"],
  VAT_SALE: ["document_number", "issue_date", "receipt_date", "contractor_nip", "contractor_name", "net", "vat", "gross", "register_name", "vat_period"],
  LEDGER: ["document_number", "accounting_date", "operation_date", "description", "account", "account_opposite", "account_wn", "account_ma", "amount_wn", "amount_ma", "journal", "contractor_name", "contractor_nip"],
  ACCOUNT_PLAN: ["account_number", "name", "account_type", "is_active", "jpk_s_12_1"],
  SETTLEMENTS: ["document_number", "contractor_name", "contractor_nip", "due_date", "payment_date", "amount", "paid_amount", "remaining_amount", "account", "status"],
  BANK: ["document_number", "operation_date", "description", "amount", "contractor_name", "account", "status"],
  JPK_DECLARATIONS: [],
  CONTRACTORS: ["contractor_name", "contractor_nip", "account", "status"],
  DOCUMENTS: ["document_number", "issue_date", "description", "status"],
  FIXED_ASSETS: ["document_number", "issue_date", "description", "account", "amount", "status"],
  HR_PAYROLL: [],
};

export const REQUIRED_BY_KIND = {
  VAT_PURCHASE: new Set(["document_number", "net", "vat", "gross"]),
  VAT_SALE: new Set(["document_number", "net", "vat", "gross"]),
  LEDGER: new Set(["document_number", "amount_wn", "amount_ma"]),
  ACCOUNT_PLAN: new Set(["account_number"]),
  SETTLEMENTS: new Set(["document_number", "amount"]),
  BANK: new Set(["amount", "description"]),
};

export const FIELD_LABELS = {
  document_number: "Numer dokumentu",
  issue_date: "Data wystawienia",
  receipt_date: "Data wpływu",
  vat_period: "Okres VAT",
  contractor_name: "Kontrahent",
  contractor_nip: "NIP kontrahenta",
  net: "Kwota netto",
  vat: "Kwota VAT",
  gross: "Kwota brutto",
  vat_rate: "Stawka VAT",
  register_name: "Rejestr",
  jpk_codes: "Kody JPK",
  accounting_date: "Data księgowania",
  operation_date: "Data operacji",
  description: "Opis",
  account_wn: "Konto Wn",
  account_ma: "Konto Ma",
  account_opposite: "Konto przeciwstawne",
  amount_wn: "Kwota Wn",
  amount_ma: "Kwota Ma",
  journal: "Dziennik",
  account_number: "Numer konta",
  name: "Nazwa",
  account_type: "Typ konta",
  is_active: "Czy aktywne",
  jpk_s_12_1: "Znacznik JPK S_12_1",
  jpk_s_12_2: "Znacznik JPK S_12_2",
  jpk_s_12_3: "Znacznik JPK S_12_3",
  due_date: "Termin płatności",
  payment_date: "Data płatności",
  amount: "Kwota",
  paid_amount: "Kwota zapłacona",
  remaining_amount: "Kwota pozostała",
  account: "Konto",
  status: "Status",
  condition: "Warunek",
  amount_expression: "Definicja kwoty",
};

export const FIELD_HELP_TEXTS = {
  document_number: "Numer faktury, dokumentu, dowodu księgowego albo wyciągu.",
  issue_date: "Data wystawienia dokumentu z eksportu Optimy.",
  receipt_date: "Data wpływu lub otrzymania dokumentu.",
  vat_period: "Miesiąc lub okres rozliczenia VAT.",
  contractor_name: "Nazwa klienta, dostawcy albo innego kontrahenta.",
  contractor_nip: "NIP używany do kontroli duplikatów i danych kontrahenta.",
  net: "Wartość netto dokumentu.",
  vat: "Kwota podatku VAT.",
  gross: "Wartość brutto dokumentu.",
  vat_rate: "Stawka VAT, np. 23%, 8%, 5%, 0%, zw.",
  register_name: "Nazwa rejestru VAT lub źródła dokumentu.",
  jpk_codes: "Oznaczenia GTU, procedury lub inne kody JPK.",
  accounting_date: "Data księgowania zapisu.",
  operation_date: "Data operacji gospodarczej lub bankowej.",
  description: "Treść operacji, opis księgowania albo tytuł przelewu.",
  account_wn: "Konto po stronie Wn.",
  account_ma: "Konto po stronie Ma.",
  account_opposite: "Konto przeciwne z zapisu księgowego Optimy.",
  amount_wn: "Kwota po stronie Wn.",
  amount_ma: "Kwota po stronie Ma.",
  journal: "Dziennik lub rejestr księgowy.",
  account_number: "Numer konta z planu kont.",
  name: "Nazwa konta, schematu albo pozycji.",
  account_type: "Rodzaj konta, np. bilansowe, wynikowe, rozrachunkowe.",
  is_active: "Informacja, czy konto jest aktywne.",
  jpk_s_12_1: "Znacznik JPK_KR_PD dla konta.",
  due_date: "Termin zapłaty rozrachunku.",
  payment_date: "Data rzeczywistej płatności.",
  amount: "Kwota dokumentu, rozrachunku albo przelewu.",
  paid_amount: "Część już zapłacona.",
  remaining_amount: "Saldo pozostające do rozliczenia.",
  account: "Konto rozrachunkowe, bankowe albo schematowe.",
  status: "Status rozrachunku lub pozycji.",
  condition: "Warunek użycia schematu księgowego.",
  amount_expression: "Sposób wyliczenia kwoty w projekcie schematu.",
};

export const ALIASES = {
  document_number: ["nr dokumentu", "numer dokumentu", "numer dowodu", "nr dowodu", "dokument", "dowod", "dowod ksiegowy", "dowod sprzedazy", "dowod zakupu", "numer zapisu"],
  issue_date: ["data wystawienia", "data dokumentu", "data faktury"],
  receipt_date: ["data wplywu", "data otrzymania"],
  contractor_name: ["kontrahent", "nazwa kontrahenta", "nazwa dostawcy", "nazwa podmiotu", "podmiot", "nazwa", "firma"],
  contractor_nip: ["nip", "nip kontrahenta", "nr kontrahenta", "nr dostawcy"],
  net: ["netto", "wartosc netto", "kwota netto"],
  vat: ["vat", "kwota vat", "podatek vat", "podatek naliczony"],
  gross: ["brutto", "wartosc brutto", "kwota brutto"],
  vat_rate: ["stawka vat", "vat procent", "stawka"],
  register_name: ["rejestr", "rejestr vat"],
  vat_period: ["okres vat", "okres rozliczeniowy"],
  accounting_date: ["data ksiegowania", "data zapisu"],
  description: ["opis", "tresc"],
  account_wn: ["konto wn", "wn"],
  account_ma: ["konto ma", "ma"],
  account_opposite: ["konto przeciw", "konto przeciw.", "konto przeciwstawne", "konto przeciwne"],
  amount_wn: ["kwota wn", "wn kwota"],
  amount_ma: ["kwota ma", "ma kwota"],
  journal: ["dziennik", "nr dziennika", "numer w dzienniku", "nr dziennika czastkowy", "nr dziennika cząstkowego"],
  account_number: ["konto", "numer konta", "nr konta"],
  name: ["nazwa konta", "nazwa"],
  account_type: ["typ konta", "rodzaj konta"],
  amount: ["kwota", "wartosc", "wartosc bilansowa", "wartosc kosztowa"],
  paid_amount: ["zaplacono", "kwota zaplacona"],
  remaining_amount: ["pozostalo", "saldo", "kwota pozostala"],
  due_date: ["termin platnosci"],
  payment_date: ["data platnosci"],
  operation_date: ["data operacji"],
  account: ["konto rozrachunkowe", "konto"],
  is_active: ["czy aktywne", "aktywne", "aktywny"],
  jpk_s_12_1: ["znacznik jpk s_12_1", "s_12_1", "jpk s_12_1"],
  jpk_s_12_2: ["znacznik jpk s_12_2", "s_12_2", "jpk s_12_2"],
  jpk_s_12_3: ["znacznik jpk s_12_3", "s_12_3", "jpk s_12_3"],
  status: ["status"],
};

export const TEMPLATES = {
  FZ_VAT_100: {
    name: "FZ koszt VAT 100%",
    condition: "document_type == 'FZ'",
    lines: [
      ["WN", "{{cost_account}}", "net", "Koszt netto"],
      ["WN", "{{vat_account}}", "vat", "VAT naliczony"],
      ["MA", "{{supplier_account}}", "gross", "Rozrachunek z dostawca"],
    ],
  },
  FZ_PALIWO_50: {
    name: "FZ paliwo VAT 50%",
    condition: "document_type == 'FZ' and category == 'PALIWO'",
    lines: [
      ["WN", "{{fuel_account}}", "net + vat_nondeductible", "Koszt paliwa"],
      ["WN", "{{vat_account}}", "vat_deductible", "VAT odliczalny"],
      ["MA", "{{supplier_account}}", "gross", "Rozrachunek z dostawca"],
    ],
  },
  FZ_BEZ_VAT: {
    name: "FZ bez VAT",
    condition: "document_type == 'FZ' and vat == 0",
    lines: [
      ["WN", "{{cost_account}}", "gross", "Koszt brutto"],
      ["MA", "{{supplier_account}}", "gross", "Rozrachunek z dostawca"],
    ],
  },
  FS_23: {
    name: "FS sprzedaz krajowa 23%",
    condition: "document_type == 'FS' and vat_rate == '23%'",
    lines: [
      ["WN", "{{customer_account}}", "gross", "Naleznosc od odbiorcy"],
      ["MA", "{{revenue_account}}", "net", "Przychod"],
      ["MA", "{{vat_due_account}}", "vat", "VAT nalezny"],
    ],
  },
  WB_BANK_FEE: {
    name: "WB oplata bankowa",
    condition: "document_type == 'WB' and kind == 'BANK_FEE'",
    lines: [
      ["WN", "{{financial_cost_account}}", "amount", "Koszt bankowy"],
      ["MA", "{{bank_account}}", "amount", "Rachunek bankowy"],
    ],
  },
  AMORT: {
    name: "AMORT",
    condition: "document_type == 'AMORT'",
    lines: [
      ["WN", "{{depreciation_cost_account}}", "amount", "Koszt amortyzacji"],
      ["MA", "{{accumulated_depreciation_account}}", "amount", "Umorzenie"],
    ],
  },
  LP: {
    name: "LP lista plac",
    condition: "document_type == 'LP'",
    lines: [
      ["WN", "{{salary_cost_account}}", "gross_salary", "Koszt wynagrodzen"],
      ["MA", "{{employee_liability_account}}", "net_salary", "Wyplata netto"],
      ["MA", "{{tax_liability_account}}", "tax", "Podatek"],
      ["MA", "{{social_security_account}}", "social_security", "ZUS"],
    ],
  },
};

export const VIEW_TITLES = {
  database: ["Baza SQL", "Podłączenie lokalnej kopii Optimy z pliku BAK/BAC."],
  audit: ["Audyt", "Import, podglad i szybka walidacja eksportu."],
  mapping: ["Mapowanie", "Dopasowanie kolumn z pliku do modelu kanonicznego."],
  schema: ["Schemat", "Projekt dekretow bez importu do Optimy."],
  report: ["Raport", "Eksport wynikow lokalnie z przegladarki."],
};

export const VAT_RATES = new Set(["0", "0%", "5", "5%", "8", "8%", "23", "23%", "zw", "np", "oo"]);
