export function createInitialState() {
  return {
    headers: [],
    rows: [],
    reportHeaders: [],
    reportRows: [],
    reportRawRows: [],
    reportNotes: [],
    reportSource: null,
    reportDataStatus: "idle",
    reportDataKey: "",
    reportDataError: "",
    reportChartEnabled: false,
    reportFilterValues: {},
    favoriteReports: [],
    backups: [],
    availableData: [],
    availableYears: [],
    currentModule: "",
    currentView: "start",
    currentReportKey: "package-status",
    format: "-",
    fileName: "",
  };
}
