export function createInitialState() {
  return {
    headers: [],
    rows: [],
    reportHeaders: [],
    reportRows: [],
    reportRawRows: [],
    reportNotes: [],
    reportSource: null,
    reportOptimaFilter: null,
    reportOptimaFilterStatus: "idle",
    reportOptimaFilterError: "",
    reportDataStatus: "idle",
    reportDataKey: "",
    reportDataError: "",
    reportChartEnabled: false,
    reportToolbarMenuOpen: "",
    reportFilterValues: {},
    reportControlSelections: {},
    reportAlertSelections: {},
    reportColumnOrder: [],
    reportHiddenColumns: {},
    reportInteractiveStates: {},
    adminSourceFile: null,
    adminSourceFileName: "",
    adminSourceFormat: "",
    adminPreviewHeaders: [],
    adminPreviewRows: [],
    adminValidationStatus: "idle",
    adminValidationResult: null,
    adminValidationError: "",
    favoriteReports: [],
    backups: [],
    availableData: [],
    availableYears: [],
    importYears: ["2025", "2026"],
    currentModule: "",
    currentView: "start",
    currentReportKey: "package-status",
    expandedSidebarGroupId: "",
    format: "-",
    fileName: "",
  };
}
